name: Daily Fetch Upstream And Tag Sites

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: "https://github.com/CorentinTh/it-tools.git"
  # Required, token to authenticate bot, could use ${{ secrets.GITHUB_TOKEN }}
  # Over here, we use a PAT instead to authenticate workflow file changes.
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  # Optional, defaults to main
  UPSTREAM_BRANCH: "main"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: ""
  # Optional fetch arguments
  FETCH_ARGS: ""
  # Optional merge arguments
  MERGE_ARGS: "--no-ff"
  # Optional push arguments
  PUSH_ARGS: ""
  # Optional toggle to spawn time logs (keeps action active)
  SPAWN_LOGS: "false" # "true" or "false"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: add content path
        run: |
          sed -i 's/"build": "/"build": "BASE_URL=\/mirror\/it-tools \&\& /' package.json

      - name: Install dependencies
        run: pnpm i

      - name: Build the app
        run: pnpm build

      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r it-tools dist

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::it-tools_$(date +"%Y.%m.%d_%H_%M_%S")"
      - name: GH Release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files:  it-tools.zip